---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubus-deployment
spec:
  selector:
    matchLabels:
      app: cubus
  replicas: 2
  template:
    metadata:
      labels:
        app: cubus
    spec:
      containers:
      - name: cubus
        image: bapathuashokreddy/cubus
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.25"
            memory: "128Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cubus-service
spec:
  selector:
    app: cubus
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
