apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubus-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cubus
  template:
    metadata:
      labels:
        app: cubus
    spec:
      containers:
      - name: cubus
        image: bapathuashokreddy/cubus
---
apiVersion: v1
kind: Service
metadata:
  name: cubus-service
spec:
  selector:
    app: cubus
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
